<?php echo CHtml::button('Editar',
							array('submit' => array('/militar/update/'.$model->id),
									'id'=>'detalhe-update',
									'name'=>'detalhe-update',
									'class'=>'btn btn-primary'
									)
							); ?>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'htmlOptions'=>array('class'=>'table table-striped table-hover'),
	'attributes'=>array(
		//'id',
		'saram',
		'idPosto.nome',
		'idQuadro.sigla',
		'idEspecialidade.nome',
		'idEspecialidade.sigla',
		'nome_completo',
		'nome_guerra',
		'foto',
		'antiguidade',
		'nascimento',
		'naturalidade0.nome',
		'ufNaturalidade.nome',
		'estadoCivil.tipo',
		//'estado_civil',
		'identidade',
		'cpf',
		'rc_ra',
		'pasep',
		'sexo0.nome',
		'tipoSanguineo.nome',
		'carteira_motorista',
		'cat_hab',
		'titulo_eleitoral',
		'secao_eleitoral',
		'zona_eleitoral',
		//'comportamento',
		'comportamento0.nome',
		'om0.sigla',
		'divisao0.nome',
		'subdivisao0.nome',
		'secao0.nome',
		'subsecao0.nome',
		//'data_inclusao',
		//'data_alteracao',
		'data_apres_om',
		'data_praca',
	),
)); ?>